on:
  workflow_dispatch:
  push:
    branches:
      - alpha
      - beta
      - stable
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    uses: mrbeam/mrb-workflows/.github/workflows/build.yml@feature/SW-1965-cleanup-sonarcloud-config-files
    secrets: inherit
